### ISSUE TITLE
First section sticks when scrolling down

### ISSUE THREAD

**Issue by deivuh** [allright/ASFloatingHeadersFlowLayout#2]
Thanks for this, it's working great, but I'm having an issue: 

If I scroll down the first section's header sticks instead of moving along with the rows. What would I have to do to fix this?

**Comment by deivuh** [comment]
Nevermind, I was able to fix this by adding this:

```
        if offset < 0 {
            invalidatedIndexPaths.removeAll()
        }
```

Inside `invalidationContextForBoundsChange` method

**Comment by allright** [comment]
I just corrected it the other way, look at commit:
https://github.com/allright/ASFloatingHeadersFlowLayout/commit/cca0987c20e7c61884d3baed3de16091eeb17838

**Comment by deivuh** [comment]
Thanks! It does work better that way :)
