### ISSUE TITLE
Does not work if referenceSizeForHeaderInSection returns CGSizeZero

### ISSUE THREAD

**Issue by MaximBoyarskiy** [allright/ASFloatingHeadersFlowLayout#4]
Hello Andrey,

Thank you for ASFloatingHeadersFlowLayout. It works great!
I want to use editing mode in my collection view so I toggle editing and change number of sections to 1 and try to hide/disable header (i want to implement it in common table view way). However if referenceSizeForHeaderInSection returns CGSizeZero then super.layoutAttributesForSupplementaryViewOfKind in ASFloatingHeadersFlowLayout.prepareLayout return nil and errors happens.

How should I hide/disable header in ASFloatingHeadersFlowLayout in a proper way?

Thank you in advance!

**Comment by allright** [comment]
Proper way to use native UICollectionViewFlowLayout from iOS9, it already has floatingHeaders embedded. Recommend to not use ASGloatingHeadersFlowLayout any more it is deprecated.

**Comment by MaximBoyarskiy** [comment]
I have to support iOS8 compatibility.

**Comment by allright** [comment]
I think you can try to improve ASFloatingHeadersFlowLayout as you need and
make push request to repo:)))
I have no time to deep into code right now, sorry and good luck!)
Ср, 10 авг. 2016 г. в 13:53, Maxim Boyarskiy notifications@github.com:
